### ISSUE TITLE
Custom picker width

### ISSUE THREAD

**Issue by RohovDmytro** [tunoltd/emoji-mart-native#139]
I believe it's a straightforward reqeuest.

I am quite new to react native world so I might not get something. But can we get an option to set the width of the picker?

My use case: using this picker as a keyboard.

Thanks!

**Comment by pederjohnsen** [comment]
Hey @rg4real, thanks for the feature request :)

There's already this: https://github.com/tunoltd/emoji-mart-native/issues/69
But that might still be a long way away, so I'll try find some time during next week to investigate if a custom picker width could work :ok_hand:

**Comment by rg4real** [comment]
> There's already this: #69
Not sure if that is the right issue. 

?

> But that might still be a long way away, so
You are AWESOME. :)

**Comment by rg4real** [comment]
Meanwhile I will try to build my custom picker with custom width using `NimbleEmoji` (and maybe other) component.

**Comment by pederjohnsen** [comment]
You said your use case is `using this picker as a keyboard.`, that task is to create a slack like emoji "keyboard" ie:
<img src="https://user-images.githubusercontent.com/1238485/77938668-fd221780-72ad-11ea-94ee-cf445e9abebb.jpg" width="300" height="279">
