### ISSUE TITLE
Unicode 11 emojis not present in data 🥰🥴🦘

### ISSUE THREAD

**Issue by dancherb** [tunoltd/emoji-mart-native#150]
There's a bunch of emojis that are now present on standard Android and Apple phones that aren't present in the emoji data at the paths below, and so don't come up in the picker.
```
 emoji-mart-native/data/google.json 
 emoji-mart-native/data/apple.json 
```

These include the essential "kangaroo", "smiling face with hearts" and "woozy face" as examples.

Is there any progress on these - what would it entail to include? Thanks :)

**Comment by pederjohnsen** [comment]
Hey @dancherb, I think these are included in [`missive/emoji-mart`](https://github.com/missive/emoji-mart/) now, so they will be available here as soon as I get to port over all the latest changes from there 👌. I'll try find the energy to do this over the weekend :)

**Comment by dancherb** [comment]
Sweet, love you Peder

**Comment by pederjohnsen** [comment]
@dancherb just letting you know I've brought the lib up to date with [`emoji-mart`](https://github.com/missive/emoji-mart) here: https://github.com/tunoltd/emoji-mart-native/pull/152 but haven't had time to test that everything is working correctly or if I've missed anything.

I'm hoping to get it properly tested and checked within the next couple of days, if all good I'll get the new release out by the end of the week :)

**Comment by dancherb** [comment]
Awesome, thanks :) I had a look at the files changed and saw there's lots of new stuff, reformatting etc going on as well. This is probably all very useful but I've monkey patched my installation quite a lot (you would cry if you saw it) so do you know if it would be safe to just copy the new `/data/google.json `and `data/apple.json` for the new emojis?

**Comment by pederjohnsen** [comment]
@dancherb it might be enough to copy the files as long as you also make this change: https://github.com/tunoltd/emoji-mart-native/commit/ecec08d6386857858839e3f855db2ed46200fcc1#diff-ef55c2bdd21683dfed9185c9640f7800L5-R6

**Comment by dancherb** [comment]
Woo, we have kangaroos. Thanks man 😁
