### ISSUE TITLE
Scroll causing iPhone to Resrping

### ISSUE THREAD

**Issue by destinybonavita** [tunoltd/emoji-mart-native#196]
**Describe the bug**
I added `<NimblePicker set='apple' data={data} />` to one of my components and when I go to scroll my iPhone resprings and reboots.

**To Reproduce**
I simply installed the module, added it to my component and tried to scroll. 

**Expected behavior**
It scrolls normally 😅

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 11 Pro Max
 - OS: [e.g. iOS8.1] iOS 13.4.1

**Additional context**
My project is using the newest version of Expo if that helps.

**Comment by destinybonavita** [comment]
I also tried with using `import { ModalPicker } from 'emoji-mart-native'` and scrolling anywhere is causing a respring

**Comment by destinybonavita** [comment]
(Sorry to keep commenting)

It seems that the problem is tied to loading more data. I clicked one of the categories and that caused the respring as well

**Comment by destinybonavita** [comment]
After a little more testing, it appears the problem is because of the emoji sheet size. Bringing it down to 16 stopped the crashes.

**Comment by destinybonavita** [comment]
Each emoji does take quite a bit of time to load in though, about 15+ seconds each.

**Comment by pederjohnsen** [comment]
Thanks for reporting this bug @destinybonavita :)

I've not had much time yet to properly test this on iOS, and not tested with expo at all.

For the load time, are you using local sprite sheets? if not, I would recommend you do and include the assets in the app package. This should give you the best performance load wise.
https://github.com/tunoltd/emoji-mart-native#spritesheetfn

**Comment by destinybonavita** [comment]
Hi @pederjohnsen ! 

Thanks for getting back so quickly. I did try to use local sprites, but I might not of been including them in the app package correctly. 

I did realize that there's a `native` property and that did exactly what I needed it to. Working great now! 

Thanks :)
