### ISSUE TITLE
Is there a way to get the full width of the screen with a picker?

### ISSUE THREAD

**Issue by drexelfitzrosh** [tunoltd/emoji-mart-native#198]
I have  use the style to change the size on the picker I use width and height. The height is working properly but the width seems it not reflecting any changes.

**Comment by pederjohnsen** [comment]
Duplicate: https://github.com/tunoltd/emoji-mart-native/issues/139

@drexelfitzrosh there's no way to do it atm, I've been meaning to investigate a solution for this but haven't gotten around to it yet.

What is your use case for making it wider?

**Comment by drexelfitzrosh** [comment]
This will be used in chats like messenger or slack.. is there any workaround?

**Comment by pederjohnsen** [comment]
To make it more like a keyboard integrated picker?
<img src="https://user-images.githubusercontent.com/1238485/77938668-fd221780-72ad-11ea-94ee-cf445e9abebb.jpg" width="300" height="279">

There's no workaround atm no, the width is unfortunately hard coded.
You could use just the `<Emoji/>` component and data etc and build your own (I know some people have done this)

**Comment by drexelfitzrosh** [comment]
thanks

**Comment by medonagy45** [comment]
you can do that by adding perLine emoji to that  `perLine={Math.floor(Width / 42)}`
