### ISSUE TITLE
Can this be used without running babel on node_modules?

### ISSUE THREAD

**Issue by mgw-sbex** [tunoltd/emoji-mart-native#217]
**Describe the bug**
Hi, when I try to include the EmojiButton and NimblePicker in my RN app, I get 
Uncaught TypeError: Cannot read property 'style' of undefined
    at Object.<anonymous> (main.js:formatted:109603)
    at a (main.js:formatted:11)
    at Object.<anonymous> (main.js:formatted:64433)
    at a (main.js:formatted:11)
    at Object.<anonymous> (main.js:formatted:33120)
    at a (main.js:formatted:11)
    at Object.<anonymous> (main.js:formatted:109128)
    at a (main.js:formatted:11)
    at Object.<anonymous> (main.js:formatted:31082)
    at a (main.js:formatted:11)
On the line below:
👍  }(c.default.PureComponent);
    t.default = p,
    (0,
    l.default)(p, "propTypes", {
        notFound: d.default.func.isRequired,
        notFoundEmoji: d.default.string.isRequired,
        emojiProps: d.default.object.isRequired,
        style: g.ViewPropTypes.style,<----- un
        theme: d.default.oneOf(["light", "dark"])
**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pederjohnsen** [comment]
Hey @mgw-sbex, sorry for the late reply!

Are you using expo? if not which RN version are you using?

**Comment by mgw-sbex** [comment]
Hey Thanks @pederjohnsen . It's actually just Typescript React for the web... nothing native. There are no css files, only stylesheets in the components. It would be better if I could install into my tree instead of node_modules I guess.

**Comment by pederjohnsen** [comment]
If on web, I would recommend using https://github.com/missive/emoji-mart instead 🤔
