### ISSUE TITLE
Add support for emoji sheets

### ISSUE THREAD

**Issue by kubraturan** [tunoltd/emoji-mart-native#58]
Hi,

I have a local emoji sheet file, and trying to use backgroundImageFn to use that emoji sheet file with the following code:

```javascript
<Emoji
    key={i}
    set={Config.EMOJI_TYPE}
    native={Config.EMOJI_TYPE === undefined}
    sheetSize={32}
    backgroundImageFn={() => {
        switch(Config.EMOJI_TYPE) {
            case 'myemojisheet':
                return require('../assets/emojis/myemojisheet.png');
            default:
                return `https://unpkg.com/emoji-datasource-${Config.EMOJI_TYPE}@3.0.0/img/${Config.EMOJI_TYPE}/sheets-256/${64}.png`;
        }
    }}
    emoji={arr[i].emoji}
    size={20} />
```

It shows emojis which supported in this library with this code but it doesn't show my emojis. How can I solve this and show my local emojis?

**Comment by johnsenpeder** [comment]
Hi @kubraturan, sorry for the delayed response,

Unfortunately there is no `backgroundImageFn` support currently (the readme haven't been fully updated yet to reflect what this lib supports)

I'm not sure how doable using sheets is as there is no background image prop in React Native as far as I'm aware. Will do some research during the week :+1:

**Comment by kubraturan** [comment]
Okey :+1: . I'm waiting for you back.

**Comment by pederjohnsen** [comment]
@kubraturan just thought I'd let you know I'm picking this up. I've got a few ideas and will be spending the next few days trying them out! :crossed_fingers: my ideas work.

**Comment by pederjohnsen** [comment]
@kubraturan just released an alpha build [`0.5.0-alpha`](https://www.npmjs.com/package/emoji-mart-native/v/0.5.0-alpha) of the next version going out which adds the emoji sheet support!

For how to use either check the updated [example](https://github.com/tunoltd/emoji-mart-native/tree/master/example) app or the [readme](https://github.com/tunoltd/emoji-mart-native/blob/master/README.md#spritesheetfn).

It would be great if you could give it a test and let me know if you have any issues :)

**Comment by pederjohnsen** [comment]
@kubraturan not sure what platform you are building for, but unfortunately due to some bug in [React Native/fresco](https://github.com/facebook/fresco/issues/2397), emoji quality is reduced when using the sprite sheets on Android.

On left: `localImages` on right `spriteSheetFn`
![emoji_quality](https://user-images.githubusercontent.com/1238485/68577968-075f8880-0469-11ea-9b18-780f200087dd.png)

So instead of releasing it as a full replacement for `localImages` I will keep that in as a workaround.

**Comment by pederjohnsen** [comment]
@kubraturan [`0.5.0-beta`](https://www.npmjs.com/package/emoji-mart-native/v/0.5.0-beta) is now released and ready for use :ok_hand: 

Closing :)
