### ISSUE TITLE
Speed?

### ISSUE THREAD

**Issue by nonotest** [tunoltd/emoji-mart-native#68]
Hi guys, thanks for the good work.
I hope I didn't miss anything..

I am using the ModalPicker in one of my Screens and on an iphone XSMax it takes about 5 seconds to open the first time.

Is that expected ? if yes is the only way to get a better speed to only include a smaller set of icons?

Here is my code in case I am doing something wrong?

```
import emojiMartData from 'emoji-mart-native/data/apple.json';
import dataRequires from 'emoji-mart-native/data/local-images/apple';
import { ModalPicker } from 'emoji-mart-native';

<ModalPicker
        isVisible
        showCloseButton
        onPressClose={this....}
        data={emojiMartData}
        useLocalImages={localEmojis}
      
        onSelect={emoji => {
           ...
        }}
        autofocus
        data={emojiMartData}
        size={30}
        set="apple"
      />
    );
```

**Comment by pederjohnsen** [comment]
Hey @nonotest, I've not done a lot of testing on iOS yet, but in our production app on android there are no issues with it taking a long time to load the first time.

Are you having these issues only when the app is running in debug (dev) mode or also with production builds?

Might be worth doing a build of the app and see if you're still experiencing this issue.
Also maybe give the example app in this repo a go to see if you have the same issue with that? :)

I'll try do some further investigation later tonight 👌

Oh, also, are you setting `const { emojis: localEmojis } = dataRequires`?
(Don't see this in the code you pasted, but you are passing `localEmojis` in the prop)

**Comment by nonotest** [comment]
Thanks for the reply !
Yes on production build unfortunately.

Yep for localemoji, I have that. sorry forgot to add it.
What would be the best way of troubleshooting the speed?

I will do more checks on my end meanwhile !

Cheers!

**Comment by pederjohnsen** [comment]
@nonotest it would be useful to know if you have the same problem with the example app, as if you do I can use that to investigate more later 👌

**Comment by nonotest** [comment]
hello - i will check now, cheers

**Comment by nonotest** [comment]
hello - did some minimal testing  on my app (not barebones yet)  and it starts slowing down when i add
```useLocalImages={localEmojis}```
on my phone

will report with barebones later

**Comment by pederjohnsen** [comment]
Hey @nonotest I didn't have much chance to test this and then I went on holiday. Back now though so I'll try do some testing over the bank holiday weekend :ok_hand: 

Did you get to test with barebones yet? :)

**Comment by nonotest** [comment]
Sorry I haven’t had a chance yet. Just ended up rolling without localmoji
for now.

**Comment by pederjohnsen** [comment]
@nonotest I'm sorry I haven't had a chance to do any testing with this yet, I am however picking https://github.com/tunoltd/emoji-mart-native/issues/58 up which might help towards this issue.

I will probably make it so a custom emoji sheet can be provided too, so that the sheets can easily be included in the app package for hopefully even faster loading :ok_hand:

**Comment by pederjohnsen** [comment]
Hey @nonotest, I just released an alpha build [`0.5.0-alpha`](https://www.npmjs.com/package/emoji-mart-native/v/0.5.0-alpha) of the next version going out which adds the emoji sheet support!

For how to use either check the updated [example](https://github.com/tunoltd/emoji-mart-native/tree/master/example) app or the [readme](https://github.com/tunoltd/emoji-mart-native/blob/master/README.md#spritesheetfn).

It would be great if you could give it a test and let me know if this helps with the speed issue!
For iOS I would recommend adding the emoji sheets you need to the platform specific app package for the best results :ok_hand:

**Comment by pederjohnsen** [comment]
@nonotest using `localImages` definitely is quite slow on iOS, [`0.5.0-beta`](https://www.npmjs.com/package/emoji-mart-native/v/0.5.0-beta) is now released and ready for use, using the emoji sheets should help speed it up (especially when adding the sheets to the app package).

Closing this for now, feel free to re-open if needed :ok_hand:

**Comment by nonotest** [comment]
thanks will try and report back!

**Comment by nonotest** [comment]
yep definitely much better!

**Comment by pederjohnsen** [comment]
@nonotest glad to hear :+1:
