### ISSUE TITLE
Slow bundle times with useLocalImages

### ISSUE THREAD

**Issue by danfang** [tunoltd/emoji-mart-native#72]
I started using useLocalImages to speed up in-app emoji load times for the ModalPicker and Emoji objects. Here's some example usage:

```
import appleImages from "emoji-mart-native/data/local-images/apple"
import googleImages from "emoji-mart-native/data/local-images/google"
import appleEmojiData from "emoji-mart-native/data/apple.json"
import googleEmojiData from "emoji-mart-native/data/google.json"

const appleEmojis = appleImages.emojis
const googleEmojis = googleImages.emojis

const data = Platform.select({
    ios: appleEmojiData,
    android: googleEmojiData,
    default: appleEmojiData,
  })

const localImages = Platform.select({
    ios: appleEmojis,
    android: googleEmojis,
    default: appleEmojis,
  })

...
<ModalPicker set="apple" data={data} useLocalImages={localImages} />
```

This has worked well for loading the emojis, but my bundle build times (```react-native run-android --variant=release``` and in XCode) have gone from 5 minutes (pre-change) to around 15 minutes after adding local emoji support. 

Any tips?  If you can point to some resources on how to fix this, I'm happy to make a PR as well.

**Comment by pederjohnsen** [comment]
@danfang Hi, we've not experienced any bundle build issues for android apps (we do find that iOS bundles seem to take longer to build in general compared to android builds though).

We've not used `react-native run-android --variant=release` before, I'll see if I can make some time for testing this a bit after work today :ok_hand: 

Are you doing both builds on a mac?

**Comment by danfang** [comment]
> @danfang Hi, we've not experienced any bundle build issues for android apps (we do find that iOS bundles seem to take longer to build in general compared to android builds though).
> 
> We've not used `react-native run-android --variant=release` before, I'll see if I can make some time for testing this a bit after work today 👌
> 
> Are you doing both builds on a mac?

Yes, MacBook Air (Retina, 13-inch, 2018) - Mojave 10.14.6

Here are the relevant dependencies I'm using:

```
"react": "16.8.6"
"react-native": "0.60.4"
"emoji-datasource-apple": "^4.1.0"
"emoji-datasource-google": "^4.1.0"
"emoji-mart-native": "^0.4.7-beta"
```

**Comment by pederjohnsen** [comment]
@danfang I guess removing one of the data sources and seeing if it makes a difference would confirm it's probably the number of individual images..

Figuring a way to use icon sheets is on the roadmap, but it will probably require a slight "hack" :thinking:

**Comment by pederjohnsen** [comment]
Hey @danfang, I just released an alpha build [`0.5.0-alpha`](https://www.npmjs.com/package/emoji-mart-native/v/0.5.0-alpha) of the next version going out which adds the emoji sheet support!

For how to use either check the updated [example](https://github.com/tunoltd/emoji-mart-native/tree/master/example) app or the [readme](https://github.com/tunoltd/emoji-mart-native/blob/master/README.md#spritesheetfn).

It would be great if you could give it a test!
For the best possible result in app, I'd suggest adding the emoji sheets you need to the platform specific app package. This would also remove the need for including the `emoji-datasource-...` dependencies.

**Comment by pederjohnsen** [comment]
@danfang [`0.5.0-beta`](https://www.npmjs.com/package/emoji-mart-native/v/0.5.0-beta) is now released and ready for use.

Closing, if you're still having problems when using emoji sheets, feel free to re-open :ok_hand:

**Comment by sibelius** [comment]
@danfang how have you solved this?
