### ISSUE TITLE
Getting error: `componentWillReceiveProps` is deprecated

### ISSUE THREAD

**Issue by luigbren** [tunoltd/emoji-mart-native#73]
Hi friends, I need your help to solve an error, when I run this component I get the error "componentWillReceiveProps is deprecated ... Use static getDerivedStateFromProps" in the nimble-picker.js file

`        key: 'componentWillReceiveProps',
        value: function componentWillReceiveProps(props) {
            if (props.skin) {
                this.setState({
                    skin: props.skin
                });
            } else if (props.defaultSkin && !_skin2.default.get()) {
                this.setState({
                    skin: props.defaultSkin
                });
            }
        }`

**Comment by pederjohnsen** [comment]
Hey @luigbren,

Which version of React are you using?

**Comment by pederjohnsen** [comment]
Closing for https://github.com/tunoltd/emoji-mart-native/issues/74
